const REQUEST_HOME_PRODUCTS = 'REQUEST_HOME_PRODUCTS';
const RECEIVE_HOME_PRODUCTS = 'RECEIVE_HOME_PRODUCTS';
const RECEIVE_SINGLE_PRODUCT = 'RECEIVE_SINGLE_PRODUCT';
const REQUEST_SINGLE_PRODUCT = 'REQUEST_SINGLE_PRODUCT';

export default {
    REQUEST_HOME_PRODUCTS,
    RECEIVE_HOME_PRODUCTS,
    REQUEST_SINGLE_PRODUCT,
    RECEIVE_SINGLE_PRODUCT,
}