const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
const RECEIVE_PARTIAL_PRODUCT = 'RECEIVE_PARTIAL_PRODUCT';

export default {
    REQUEST_PRODUCTS,
    RECEIVE_PRODUCTS,
    RECEIVE_PARTIAL_PRODUCT
}