# Generated by Django 3.0.4 on 2020-05-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_delete_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
