# Generated by Django 3.0.4 on 2020-05-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200508_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('1', 'Popular'), ('2', 'New Arrivals'), ('3', 'Deals')], default='1', max_length=1, verbose_name='Tag'),
        ),
    ]
