# Generated by Django 3.0.4 on 2020-03-29 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instore_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instoreuser',
            old_name='is_admin',
            new_name='is_owner',
        ),
    ]
