# Generated by Django 3.0.4 on 2020-03-29 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instore_user', '0002_auto_20200329_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='instoreuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instoreuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
