# Generated by Django 3.0.4 on 2020-04-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(default='', max_length=30, verbose_name='Your Name')),
                ('address', models.TextField(default='', verbose_name='Address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
