# Generated by Django 3.0.4 on 2020-05-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instore_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instoreuser',
            options={'verbose_name': 'Instore User'},
        ),
        migrations.AlterModelOptions(
            name='onetimepassword',
            options={'verbose_name': 'One Time Password'},
        ),
    ]
