# Generated by Django 3.0.4 on 2020-05-17 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_tag'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionproduct',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Tag'),
        ),
    ]
