# Generated by Django 3.0.4 on 2020-04-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200426_0932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
