# Generated by Django 3.0.4 on 2020-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('popular', 'Popular'), ('new_arrivals', 'New Arrivals'), ('deals', 'Deals')], default='popular', max_length=15, verbose_name='Tag'),
        ),
    ]
