# Generated by Django 3.0.4 on 2020-05-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_store_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='button_color',
            field=models.CharField(default='#3b3650', max_length=7, verbose_name='Button Color'),
            preserve_default=False,
        ),
    ]
