const FETCH_STORE_DETAIL_REQUEST = 'FETCH_STORE_DETAIL_REQUEST';
const FETCH_STORE_DETAIL_SUCCESS = 'FETCH_STORE_DETAIL_SUCCESS';
const FETCH_STORE_DETAIL_FAILED = 'FETCH_STORE_DETAIL_FAILED'

export default {
    FETCH_STORE_DETAIL_REQUEST,
    FETCH_STORE_DETAIL_SUCCESS,
    FETCH_STORE_DETAIL_FAILED
}