const REQUEST_STORE_DETAILS = 'REQUEST_STORE_DETAILS';
const RECEIVE_STORE_DETAILS = 'RECEIVE_STORE_DETAILS';
const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';

export default {
    REQUEST_STORE_DETAILS,
    RECEIVE_STORE_DETAILS,
    REQUEST_PRODUCTS,
    RECEIVE_PRODUCTS
}