# Generated by Django 3.0.4 on 2020-05-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='Store Name')),
                ('domain', models.CharField(max_length=30, unique=True, verbose_name='Domain Name')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Webdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/logo')),
                ('theme_color', models.CharField(max_length=7, verbose_name='Theme Color Code')),
                ('accent_color', models.CharField(max_length=7, verbose_name='Accent Color Code')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='store/spotlights')),
                ('order', models.IntegerField(blank=True, default=10, null=True, verbose_name='Order (Priority: 10-1)')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=12, verbose_name='Tag Name')),
                ('slug', models.SlugField(verbose_name='Tag Slug')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='store.Store')),
            ],
            options={
                'unique_together': {('store', 'slug')},
            },
        ),
    ]
