# Generated by Django 3.0.4 on 2020-05-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200513_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='logo',
        ),
        migrations.CreateModel(
            name='Webdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/logo')),
                ('theme_color', models.CharField(max_length=7, verbose_name='Theme Color Code')),
                ('accent_color', models.CharField(max_length=7, verbose_name='Accent Color Code')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
