# Generated by Django 3.0.4 on 2020-05-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200517_0704'),
        ('store', '0005_spotlight_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
