# Generated by Django 3.0.4 on 2020-05-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
            preserve_default=False,
        ),
    ]
