# Generated by Django 3.0.4 on 2020-05-17 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_tag_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='store.Store'),
        ),
    ]
