# Generated by Django 3.0.4 on 2020-05-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200517_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Tag Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('store', 'slug')},
        ),
    ]
