# Generated by Django 3.0.4 on 2020-04-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200425_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile_no',
        ),
    ]
